# Generated by Django 3.0.6 on 2020-05-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200517_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='features',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
